;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-delete-forward
        c-electric-paren
        c-electric-slash
        c-electric-star
        c-indent-line-or-region
        crux-move-beginning-of-line
        delete-horizontal-space
        ))

(setq mc/cmds-to-run-once
      '(
        ))
